#配置eureka服务名
spring:
  application:
    name: cloud-eureka-provider
  #配置jpa
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
      
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
    
#配置日志信息
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch: DEBUG
    
#配置端口 
server:
  port: 8082
  
#配置eureka信息
eureka:
  client:
    service-url:
      defaultZone: http://root:duguxiaobiao@localhost:8761/eureka
      
#配置服务显示ip以及显示格式
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port:${random.value}}